version: 5.0.0-{build}
clone_folder: c:\projects\nlog
build_script:
  - ps: .\build.ps1

test_script:
  - ps: .\run-tests.ps1
  
deploy:
  provider: NuGet
  api_key:
    secure: QQQ2lpOVxxjRGCF7xGtWri1yov8rDUENp7lX8y0cymZPEyV8grMMveniEti3Fr/9
  skip_symbols: false
  artifact: /artifacts\\.*\.nupkg/
  
artifacts:
  - path: 'artifacts\*.nupkg'